# Site settings
title: "Healthy Lifestyle Guide"
description: "Health and Wellness Guide: Tips for Nutrition, Fitness, and Mental Health."
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
