# Site settings
title: "Thriving Healthy"
description: "Health & Wellness Guide: Tips for Nutrition, Fitness, and Mental Health."
ga4_id: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
remote_theme: pages-themes/cayman@v0.2.0
permalink: pretty
plugins:
  - jekyll-remote-theme
collections:
  notes:
    output: true
    permalink: /notes/:path/
defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "default"