# Site settings
title: "Healthy Lifestyle Guide"
description: "Health & Wellness Guide: Tips for Nutrition, Fitness, and Mental Health."
remote_theme: pages-themes/cayman@v0.2.0
google_analytics: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
plugins:
- jekyll-remote-theme
